from sqlalchemy import create_engine, Column, Integer, String, DateTime, BigInteger, Boolean, ForeignKey, DECIMAL
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()

class Pessoa(Base):
    __table_args__ = {"schema": "Crm"}
    __tablename__ = 'Pessoa'

    Id = Column(BigInteger, primary_key=True, autoincrement=True)
    Version = Column(Integer, nullable=False)
    Tipo = Column(Integer, nullable=False)
    Nome = Column(String(50), nullable=False)
    NomeFonetico = Column(String(100), nullable=False)
    RazaoSocial = Column(String(100))
    RazaoSocialFonetica = Column(String(150))
    DataCadastro = Column(DateTime, nullable=False)
    UsuarioCadastro = Column(String(50))
    DataNascimento = Column(DateTime)
    Observacoes = Column(String)
    ObservacaoVenda = Column(String)
    ObservacaoFinanceira = Column(String)
    Foto = Column(String)  # Assuming varbinary(MAX) stores file path in this case
    Conta = Column(Boolean, nullable=False)
    Fornecedor = Column(Boolean)
    Transportadora = Column(Boolean)
    Concorrente = Column(Boolean)
    Oportunidade = Column(Boolean, nullable=False)
    Cnpj = Column(String(20))
    InscricaoEstadual = Column(String(20))
    Cpf = Column(String(20))
    Rg = Column(String(20))
    InscricaoMunicipal = Column(String(15))
    CodigoAuxiliar1 = Column(String(20))
    CodigoAuxiliar2 = Column(String(20))
    CodigoAuxiliar3 = Column(String(20))
    
    # fks
    RamoAtividade = Column(BigInteger)
    Status = Column(BigInteger)
    Carteira = Column(BigInteger)
    Grupo = Column(BigInteger)
    Segmento = Column(BigInteger)
    FormaAtuacao = Column(BigInteger)
    Cnae = Column(BigInteger)
    VendedorInterno = Column(BigInteger)    
    # RamoAtividade = Column(BigInteger, ForeignKey('RamoAtividade.Id'))
    # Status = Column(BigInteger, ForeignKey('StatusPessoa.Id'))
    # Carteira = Column(BigInteger, ForeignKey('Carteira.Id'))
    # Grupo = Column(BigInteger, ForeignKey('PessoaGrupo.Id'))
    # Segmento = Column(BigInteger, ForeignKey('Segmento.Id'))
    # FormaAtuacao = Column(BigInteger, ForeignKey('FormaAtuacao.Id'))
    # Cnae = Column(BigInteger, ForeignKey('Cnae.Id'))
    # VendedorInterno = Column(BigInteger, ForeignKey('Vendedor.Id'))
    RegimeTributario = Column(Integer)
    TipoLucro = Column(Integer)
    InscricaoSuframa = Column(String(10))
    Inativo = Column(DateTime)
    TipoEstabelecimento = Column(Integer)
    Finalidade = Column(Integer)
    DataPrimeiraVenda = Column(DateTime)
    DataUltimaVenda = Column(DateTime)
    LimiteCredito = Column(DECIMAL(19, 5))
    CondicaoPagamentoPadrao = Column(BigInteger)
    FormaPagamentoPadrao = Column(BigInteger)
    CarteiraCobrancaPadrao = Column(BigInteger)
    RestricaoFinanceira = Column(BigInteger)
    TransportadoraPadrao = Column(BigInteger)
    ContaFluxoCaixa = Column(BigInteger)
    IsentoIpi = Column(Boolean)
    SituacaoTributariaIpiIsento = Column(BigInteger)
    ObservacaoStIpiIsento = Column(BigInteger)
    IsentoIcms = Column(Boolean)
    SituacaoTributariaIcmsIsento = Column(BigInteger)
    ObservacaoStIcmsIsento = Column(BigInteger)
    IsentoPis = Column(Boolean)
    SituacaoTributariaPisIsento = Column(BigInteger)
    ObservacaoStPisIsento = Column(BigInteger)
    IsentoCofins = Column(Boolean)
    SituacaoTributariaCofinsIsento = Column(BigInteger)
    ObservacaoStCofinsIsento = Column(BigInteger)
    ClienteContaContabil = Column(String(15))
    ClienteHistoricoContabil = Column(String(5))
    ClienteTabelaPrecoPadrao = Column(BigInteger)
    ClienteCentroDeCusto = Column(BigInteger)
    IndicadorPresenca = Column(Integer)
    IndicadorInscricaoEstadual = Column(Integer)
    ControleQualidade = Column(Boolean)
    FornecedorCondicaoPagamentoPadrao = Column(BigInteger)
    FornecedorFormaPagamentoPadrao = Column(BigInteger)
    FornecedorCarteiraCobrancaPadrao = Column(BigInteger)
    FornecedorContaFluxoCaixa = Column(BigInteger)
    FornecedorTransportadoraPadrao = Column(BigInteger)
    FornecedorContaContabil = Column(String(15))
    FornecedorHistoricoContabil = Column(String(5))
    FornecedorCentroDeCusto = Column(BigInteger)
    Bomba20 = Column(Integer)
    Bomba20Hm = Column(Integer)
    Bomba50 = Column(Integer)
    Bomba50Hm = Column(Integer)
    Tambor = Column(Integer)
    Container = Column(Integer)
    ObservacaoEmbalagem = Column(String)
    Difal = Column(String(100))
    PotencialCompra = Column(Integer)
    UltimaAlteracao = Column(DateTime, nullable=False)
    UltimoLogin = Column(String(50), nullable=False)
    ObservacaoLigacoes = Column(String)
    StatusLgpd = Column(Integer)
    DataUltimoAtendimento = Column(DateTime)
    IdEstrangeiro = Column(String(20))
    Prospect = Column(Boolean)
    Funcionario = Column(Boolean)
    NomeMarcaFormaAtuacao = Column(String(100))
    MatrizGrupoEmpresarial = Column(BigInteger)

    def __repr__(self):
        return f"<Pessoa(Id={self.Id}, Nome={self.Nome}, Tipo={self.Tipo})>"